### ISSUE TITLE
nice but ..

### ISSUE THREAD

**Issue by ringo32** [fdservices/vpacman#1]
i got no Xterm  standard installed seems it search standard to xterm , and talk about config error terminal string...

after installing xterm i could catch up to the options to change the terminal.

but nice looking pacmanxg clone

**Comment by AndyM48** [comment]
Confirmed. An installed terminal and a valid terminal string are required to run vpacman. 
Proposed fix: Offer to install xterm if no terminal has been found and  open configuration options to allow the terminal and string to be changed.

**Comment by ringo32** [comment]
yeah probably Qterminal was only on this system :)  Qterminal was not known probably :) but xterm recognized good, only the configs didnt show  also it goes at start over the terminal configuration because it looks at start to an terminal.

**Comment by AndyM48** [comment]
Not sure that qterminal can be used with vpacman. The terminal string must be able to show a window title and call a command e.g.
```
xterm -title <title> -e <command>
vte --name <title> --command <command>
```
qterminal does not seem to support the title option which is required by wmctrl. If you can provide a valid terminal string then I will add it to the known terminals. Also you can set it yourself in the configuration options, Tools > Options, but  the string **must** include a title <title> and a command \<command\> in order to work.

**Comment by ringo32** [comment]
i copied over qterminal -title   and the -e     seems to work here with qterminal

**Comment by ringo32** [comment]
i removed Xterm and its depencys and vpacman runs,,   example pic i did after : https://i.imgur.com/I99Jvhg.jpg

**Comment by ringo32** [comment]
Mayby set also in PKGBUILD set Xterm as optional depency if no known terminal is installed ?

**Comment by AndyM48** [comment]
Please can you send me the exact terminal string you have used for qterminal and I will add it to the known terminals.
> Mayby set also in PKGBUILD set Xterm as optional depency if no known terminal is installed ?

Good idea

Thank you for your interest.

**Comment by ringo32** [comment]
qterminal -title <title> -e <command>    (same as xterm basicly github dont show it somehow )


i have set as this

**Comment by AndyM48** [comment]
Thank you
